name: MLflow Project CI Retrain + Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "mlflow==2.17.2" pandas scikit-learn

      - name: Run MLflow Project (local env)
        run: |
          mlflow run MLProject \
            --env-manager=local \
            -P data_path=namadataset_preprocessing/data_bersih_eksperimen.csv \
            -P target_col="Sleep Disorder" \
            -P experiment_name="CI_Retrain_RF_Baseline" \
            -P tracking_uri="file:./mlruns"

      - name: Upload MLflow runs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-mlruns
          path: mlruns

  docker:
    needs: retrain
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install MLflow + Docker deps
        run: |
          python -m pip install --upgrade pip
          pip install "mlflow==2.17.2"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build image dari MLflow Project (paling stabil)
      - name: Build Docker image from MLflow Project
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_IMAGE }}
        run: |
          if [ -z "$IMAGE_NAME" ]; then
            IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci-mlflow"
          fi

          mlflow run MLProject \
            --env-manager=local \
            --build-image \
            --docker-image-name "$IMAGE_NAME:latest" \
            -P data_path=namadataset_preprocessing/data_bersih_eksperimen.csv \
            -P target_col="Sleep Disorder" \
            -P experiment_name="CI_Retrain_RF_Baseline" \
            -P tracking_uri="file:./mlruns"

      - name: Push Docker image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_IMAGE }}
        run: |
          if [ -z "$IMAGE_NAME" ]; then
            IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci-mlflow"
          fi

          docker push "$IMAGE_NAME:latest"
