name: Workflow-CI MLflow Retrain

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn

      - name: Run MLflow Project (retrain)
        run: |
          mlflow --version
          mlflow run MLProject \
            --env-manager=local \
            -P data_path="namadataset_preprocessing/data_bersih_eksperimen.csv" \
            -P target_col="Sleep Disorder" \
            -P experiment_name="CI_Retrain_RF_Baseline" \
            -P tracking_uri="file:./mlruns"

      # SKILLED: Upload artefak hasil training (mlruns)
      - name: Upload MLflow runs folder
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns

  docker:
    needs: retrain
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install MLflow
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ADVANCE: build docker image pakai MLflow (bukan run-id)
      - name: Build Docker image with MLflow Projects
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci-mlflow:latest"
          mlflow projects build-docker -r MLProject -n "$IMAGE"

      - name: Push Docker image
        run: |
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci-mlflow:latest"
